==================================================
CNRD CRASH REPORT
==================================================

Time: 2025-04-04 21:31:21
Python version: 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]

Exception details:
Type: UnboundLocalError
Message: local variable 'enemy_program' referenced before assignment

Traceback:
Traceback (most recent call last):
  File "D:\PROJECTS\CNRD PROTOTYPE\bootstrap.py", line 51, in run_game_with_error_handling
    game.main()
  File "D:\PROJECTS\CNRD PROTOTYPE\game.py", line 866, in main
    combat_result = run_combat(player, current_enemy_daemon)
  File "D:\PROJECTS\CNRD PROTOTYPE\game.py", line 279, in run_combat
    (None, enemy_daemon, enemy_action, enemy_program, None)] # None for player indicates enemy
UnboundLocalError: local variable 'enemy_program' referenced before assignment
